### ISSUE TITLE
pfcp-smoke: failed execution

### ISSUE THREAD

**Issue by Chanbin-Bae** [omec-project/up4#302]
Hi,

recently, I read the paper about P4-based UPF and tried to use the UP4 but I met a problem with running scenario pfcp-smoke. 
When executing setup.xml, I met the problem with onos-user-key as shown in the attached image and the default password didn't work.

< Environment that I run UP4 >
- Ubuntu 20.04
- Docker 20.10.17
- Docker-compose 1.25.0
- Zulu OpenJDK 11

Can you help to solve this issue?
I will be very grateful if you can help for solving this problem. 

![Onos-User-Key failed](https://user-images.githubusercontent.com/99635565/215423557-5b907316-f407-4fdb-b8aa-a3754eeaa10d.PNG)

**Comment by daniele-moro** [comment]
Please, make sure to have a ssh-RSA key in your system. Also, you can check logs of the failed step to better understand the issue.

**Comment by Chanbin-Bae** [comment]
Thank you for your response.  Generate a ssh-RSA key with `sudo ssh-keygen` , and it works successfully.
